version: '3'

networks: 
    laravel-link:
        driver: bridge

services: 
    s-nginx:
        image: nginx:alpine
        container_name: s-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:8080"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - s-php
            - s-mysql
        networks: 
            - laravel-link

    s-mysql:
        platform: linux/amd64
        image: mysql
        container_name: s-mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel-link

    s-php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: s-php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel-link